# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aabduvak <aabduvak@42istanbul.com.tr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/29 16:32:11 by aabduvak          #+#    #+#              #
#    Updated: 2022/08/29 16:32:56 by aabduvak         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

version: "3.8"

networks:
  inception: {}

services:
  mariadb:
    env_file:
        - ./.env/mariadb.env
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    image: mariadb
    
    container_name: MARIADB
    networks:
      - inception
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    restart: unless-stopped
  
  wordpress:
    build:
      context: wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: WORDPRESS
    networks:
      - inception
    volumes:
      - "~/Desktop/inception/wordpress:/var/www/html"
    depends_on:
       - mariadb
    env_file:
       - ./.env/mariadb.env
       - ./.env/wordpress.env
    restart: unless-stopped
    
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: NGINX
    depends_on:
     - wordpress
    ports:
      - "4242:443"
    networks:
      - inception
    volumes:
      - "~/Desktop/inception/wordpress:/var/www/html"
    restart: unless-stopped